### PR TITLE
Make the base module a ABC

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by tammojan** [comment]
apercal/modules/line.py:27:5: E303 too many blank lines (2)

**Comment by gijzelaerr** [comment]
is dat alles? want dan fix ik dat morgen en merge m.

**Comment by tammojan** [comment]
Looks good (I haven't seen the ABC-construct before, but apparently it has some use).

**Comment by gijzelaerr** [comment]
it forces you to override `module_name`

**Pull request merged**
